name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print hello
        run: echo "✅ Workflow funcionando correctamente"
  

   #   - name: Check Target Frameworks
   
   #     uses: (org)/(repo).github/actions/task_check_target_frameworks.yml@feature
   #     with: 
   #      runner_label: BC-WICCN-172
   #      secrets: inherit

